# Generated by Django 5.2.6 on 2025-11-19 11:46

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('phone_number', models.CharField(help_text='Номер телефона пользователя.', max_length=15, unique=True, verbose_name='Номер телефона')),
                ('first_name', models.CharField(help_text='Имя пользователя.', max_length=50, verbose_name='Имя')),
                ('first_name_ru', models.CharField(help_text='Имя пользователя.', max_length=50, null=True, verbose_name='Имя')),
                ('first_name_uz', models.CharField(help_text='Имя пользователя.', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя.', max_length=50, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(help_text='Фамилия пользователя.', max_length=50, null=True, verbose_name='Фамилия')),
                ('last_name_uz', models.CharField(help_text='Фамилия пользователя.', max_length=50, null=True, verbose_name='Фамилия')),
                ('otp_code', models.CharField(blank=True, help_text='Одноразовый код для аутентификации.', max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, help_text='Время создания OTP-кода.', null=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Уникальный ID чата в Telegram для отправки уведомлений.', max_length=255, null=True, unique=True)),
                ('location_label', models.CharField(blank=True, help_text='Название сохраненной точки доставки (например, Дом).', max_length=100)),
                ('location_street', models.CharField(blank=True, help_text='Улица сохраненного адреса.', max_length=255)),
                ('location_building', models.CharField(blank=True, help_text='Дом сохраненного адреса.', max_length=50)),
                ('location_entrance', models.CharField(blank=True, help_text='Подъезд сохраненного адреса.', max_length=50)),
                ('location_floor', models.CharField(blank=True, help_text='Этаж сохраненного адреса.', max_length=50)),
                ('location_apartment', models.CharField(blank=True, help_text='Квартира сохраненного адреса.', max_length=50)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Широта точки доставки.', max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Долгота точки доставки.', max_digits=9, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Дом, Офис', max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('longitude', models.CharField(max_length=64, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=64, verbose_name='Широта')),
                ('entrance', models.CharField(blank=True, max_length=50, verbose_name='Подъезд')),
                ('intercom', models.CharField(blank=True, max_length=50, verbose_name='Домофон')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий для курьера')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user id')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата привязки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram аккаунт',
                'verbose_name_plural': 'Telegram аккаунты',
                'ordering': ('-linked_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-значный код для привязки Telegram', max_length=6, unique=True, verbose_name='Код привязки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(help_text='Время, до которого код действителен', verbose_name='Дата истечения')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код привязки Telegram',
                'verbose_name_plural': 'Коды привязки Telegram',
                'ordering': ('-created_at',),
            },
        ),
    ]
