# Generated by Django 5.2.8 on 2025-11-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_uz',
        ),
    ]
